# ================================================================
# JustoAI V2 - Railway Configuration
# Multi-service deployment: API + Workers
# ================================================================
# IMPORTANT: Services MUST be ordered with API first
# Railway builds in order, service names must match environment names

# ================================================================
# SERVICE 1: Web API (justoai-web)
# CRITICAL: Must use Dockerfile.api (NOT Dockerfile)
# ================================================================
[[services]]
name = "justoai-web"

[services.build]
builder = "DOCKERFILE"
# EXPLICIT: Use .api extension to avoid confusion
# Railway was using wrong Dockerfile - force clarity
dockerfilePath = "./Dockerfile.api"

[services.deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# ================================================================
# SERVICE 2: Background Workers (justoai-workers)
# EXPLICIT: Use Dockerfile.workers (renamed from Dockerfile)
# ================================================================
[[services]]
name = "justoai-workers"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.workers"

[services.deploy]
startCommand = "npx tsx src/workers/juditOnboardingWorker.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Health check disabled for worker (uses pgrep instead)
# Worker logs are monitored via Railway logs interface
