# ================================================================
# JustoAI V2 - Railway Configuration
# Single web service using Procfile for process management
# ================================================================

[[services]]
name = "justoai-web"

[services.build]
builder = "NIXPACKS"

[services.deploy]
startCommand = "node .next/standalone/justoai-v2/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
