name: Code Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run TypeScript type check
        run: npm run type-check

      - name: Check code formatting
        run: |
          echo "Checking code formatting..."
          # Add prettier check if configured
          # npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"

      - name: Analyze bundle size
        run: |
          npm run build
          echo "Build completed - analyzing bundle size..."
          # Add bundle size analysis if needed
          ls -lh .next/static/chunks/ || true

      - name: Security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

  test-coverage:
    name: Test Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Check coverage thresholds
        run: |
          echo "Checking coverage thresholds..."
          # Jest will fail if coverage is below threshold
          cat coverage/coverage-summary.json || true

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
